---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    environment: "true"
  name: production
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    environment: "true"
  name: staging